package test


func Foo(){
    var a, b, c int
    var str string
    var m vec3
    var matrix mat3
    var e error
    var b bool
    var f0 float
    var f1 float32
    var f2 float64
    var dict map[string]int
    var slc []int
    var arr [5]int


    str = "This is a message"
    e.status = 0
    e.message = str
    e.recover = false

    if a > 0{
        defer panic(e)
    }

    dict = make(0, map[string]int)
    slc = make(0, []int)
    arr[0] = 1

    return
}

func main(){
    Foo()
}